/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProfessionalsRouteImport } from './routes/professionals'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProIndexRouteImport } from './routes/pro.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ProScheduleRouteImport } from './routes/pro.schedule'
import { Route as ProProfileRouteImport } from './routes/pro.profile'
import { Route as ProPayoutRouteImport } from './routes/pro.payout'
import { Route as ProOnboardingRouteImport } from './routes/pro.onboarding'
import { Route as ProEarningsRouteImport } from './routes/pro.earnings'
import { Route as ProClientsRouteImport } from './routes/pro.clients'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppSubscriptionRouteImport } from './routes/app.subscription'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSafetyRouteImport } from './routes/app.safety'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppDisputeRouteImport } from './routes/app.dispute'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppAiRouteImport } from './routes/app.ai'
import { Route as AppPIdRouteImport } from './routes/app.p.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalsRoute = ProfessionalsRouteImport.update({
  id: '/professionals',
  path: '/professionals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProIndexRoute = ProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ProScheduleRoute = ProScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ProRoute,
} as any)
const ProProfileRoute = ProProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProRoute,
} as any)
const ProPayoutRoute = ProPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => ProRoute,
} as any)
const ProOnboardingRoute = ProOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProRoute,
} as any)
const ProEarningsRoute = ProEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => ProRoute,
} as any)
const ProClientsRoute = ProClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSafetyRoute = AppSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppDisputeRoute = AppDisputeRouteImport.update({
  id: '/dispute',
  path: '/dispute',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppPIdRoute = AppPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRouteWithChildren
  '/professionals': typeof ProfessionalsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/app/ai': typeof AppAiRoute
  '/app/book': typeof AppBookRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/me': typeof AppMeRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/search': typeof AppSearchRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/tracking': typeof AppTrackingRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/onboarding': typeof ProOnboardingRoute
  '/pro/payout': typeof ProPayoutRoute
  '/pro/profile': typeof ProProfileRoute
  '/pro/schedule': typeof ProScheduleRoute
  '/app/': typeof AppIndexRoute
  '/pro/': typeof ProIndexRoute
  '/app/p/$id': typeof AppPIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/professionals': typeof ProfessionalsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/app/ai': typeof AppAiRoute
  '/app/book': typeof AppBookRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/me': typeof AppMeRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/search': typeof AppSearchRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/tracking': typeof AppTrackingRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/onboarding': typeof ProOnboardingRoute
  '/pro/payout': typeof ProPayoutRoute
  '/pro/profile': typeof ProProfileRoute
  '/pro/schedule': typeof ProScheduleRoute
  '/app': typeof AppIndexRoute
  '/pro': typeof ProIndexRoute
  '/app/p/$id': typeof AppPIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/investors': typeof InvestorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRouteWithChildren
  '/professionals': typeof ProfessionalsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/app/ai': typeof AppAiRoute
  '/app/book': typeof AppBookRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/dispute': typeof AppDisputeRoute
  '/app/me': typeof AppMeRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/safety': typeof AppSafetyRoute
  '/app/search': typeof AppSearchRoute
  '/app/subscription': typeof AppSubscriptionRoute
  '/app/tracking': typeof AppTrackingRoute
  '/pro/clients': typeof ProClientsRoute
  '/pro/earnings': typeof ProEarningsRoute
  '/pro/onboarding': typeof ProOnboardingRoute
  '/pro/payout': typeof ProPayoutRoute
  '/pro/profile': typeof ProProfileRoute
  '/pro/schedule': typeof ProScheduleRoute
  '/app/': typeof AppIndexRoute
  '/pro/': typeof ProIndexRoute
  '/app/p/$id': typeof AppPIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/careers'
    | '/contact'
    | '/investors'
    | '/pricing'
    | '/privacy'
    | '/pro'
    | '/professionals'
    | '/services'
    | '/terms'
    | '/app/ai'
    | '/app/book'
    | '/app/bookings'
    | '/app/dispute'
    | '/app/me'
    | '/app/messages'
    | '/app/safety'
    | '/app/search'
    | '/app/subscription'
    | '/app/tracking'
    | '/pro/clients'
    | '/pro/earnings'
    | '/pro/onboarding'
    | '/pro/payout'
    | '/pro/profile'
    | '/pro/schedule'
    | '/app/'
    | '/pro/'
    | '/app/p/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/careers'
    | '/contact'
    | '/investors'
    | '/pricing'
    | '/privacy'
    | '/professionals'
    | '/services'
    | '/terms'
    | '/app/ai'
    | '/app/book'
    | '/app/bookings'
    | '/app/dispute'
    | '/app/me'
    | '/app/messages'
    | '/app/safety'
    | '/app/search'
    | '/app/subscription'
    | '/app/tracking'
    | '/pro/clients'
    | '/pro/earnings'
    | '/pro/onboarding'
    | '/pro/payout'
    | '/pro/profile'
    | '/pro/schedule'
    | '/app'
    | '/pro'
    | '/app/p/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/careers'
    | '/contact'
    | '/investors'
    | '/pricing'
    | '/privacy'
    | '/pro'
    | '/professionals'
    | '/services'
    | '/terms'
    | '/app/ai'
    | '/app/book'
    | '/app/bookings'
    | '/app/dispute'
    | '/app/me'
    | '/app/messages'
    | '/app/safety'
    | '/app/search'
    | '/app/subscription'
    | '/app/tracking'
    | '/pro/clients'
    | '/pro/earnings'
    | '/pro/onboarding'
    | '/pro/payout'
    | '/pro/profile'
    | '/pro/schedule'
    | '/app/'
    | '/pro/'
    | '/app/p/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  InvestorsRoute: typeof InvestorsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRouteWithChildren
  ProfessionalsRoute: typeof ProfessionalsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professionals': {
      id: '/professionals'
      path: '/professionals'
      fullPath: '/professionals'
      preLoaderRoute: typeof ProfessionalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/': {
      id: '/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof ProIndexRouteImport
      parentRoute: typeof ProRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/pro/schedule': {
      id: '/pro/schedule'
      path: '/schedule'
      fullPath: '/pro/schedule'
      preLoaderRoute: typeof ProScheduleRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/profile': {
      id: '/pro/profile'
      path: '/profile'
      fullPath: '/pro/profile'
      preLoaderRoute: typeof ProProfileRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/payout': {
      id: '/pro/payout'
      path: '/payout'
      fullPath: '/pro/payout'
      preLoaderRoute: typeof ProPayoutRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/onboarding': {
      id: '/pro/onboarding'
      path: '/onboarding'
      fullPath: '/pro/onboarding'
      preLoaderRoute: typeof ProOnboardingRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/earnings': {
      id: '/pro/earnings'
      path: '/earnings'
      fullPath: '/pro/earnings'
      preLoaderRoute: typeof ProEarningsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/clients': {
      id: '/pro/clients'
      path: '/clients'
      fullPath: '/pro/clients'
      preLoaderRoute: typeof ProClientsRouteImport
      parentRoute: typeof ProRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscription': {
      id: '/app/subscription'
      path: '/subscription'
      fullPath: '/app/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/safety': {
      id: '/app/safety'
      path: '/safety'
      fullPath: '/app/safety'
      preLoaderRoute: typeof AppSafetyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dispute': {
      id: '/app/dispute'
      path: '/dispute'
      fullPath: '/app/dispute'
      preLoaderRoute: typeof AppDisputeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book': {
      id: '/app/book'
      path: '/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai': {
      id: '/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/p/$id': {
      id: '/app/p/$id'
      path: '/p/$id'
      fullPath: '/app/p/$id'
      preLoaderRoute: typeof AppPIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBookRoute: typeof AppBookRoute
  AppBookingsRoute: typeof AppBookingsRoute
  AppDisputeRoute: typeof AppDisputeRoute
  AppMeRoute: typeof AppMeRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppSafetyRoute: typeof AppSafetyRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPIdRoute: typeof AppPIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBookRoute: AppBookRoute,
  AppBookingsRoute: AppBookingsRoute,
  AppDisputeRoute: AppDisputeRoute,
  AppMeRoute: AppMeRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppSafetyRoute: AppSafetyRoute,
  AppSearchRoute: AppSearchRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppIndexRoute: AppIndexRoute,
  AppPIdRoute: AppPIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProRouteChildren {
  ProClientsRoute: typeof ProClientsRoute
  ProEarningsRoute: typeof ProEarningsRoute
  ProOnboardingRoute: typeof ProOnboardingRoute
  ProPayoutRoute: typeof ProPayoutRoute
  ProProfileRoute: typeof ProProfileRoute
  ProScheduleRoute: typeof ProScheduleRoute
  ProIndexRoute: typeof ProIndexRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProClientsRoute: ProClientsRoute,
  ProEarningsRoute: ProEarningsRoute,
  ProOnboardingRoute: ProOnboardingRoute,
  ProPayoutRoute: ProPayoutRoute,
  ProProfileRoute: ProProfileRoute,
  ProScheduleRoute: ProScheduleRoute,
  ProIndexRoute: ProIndexRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  InvestorsRoute: InvestorsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRouteWithChildren,
  ProfessionalsRoute: ProfessionalsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
